from Tkinter import *
med=Tk()
med.title('Medicine Entry')
scrl = Scrollbar(med)
scrl.grid(row=1,rowspan=10 ,column=5,stick=N+E+S)
Label(med,text='Medicine Name',width=20).grid(row=0,column=0,padx=5,ipadx=5)
Label(med,text='Medicine Price',width=20).grid(row=0,column=1,padx=5,ipadx=5)
Label(med,text='Medicine Quantity',width=20).grid(row=0,column=2,padx=5,ipadx=5)
Label(med,text='Medicine EntryDate\n(DD-MM-YY)',width=20).grid(row=0,column=3,padx=5,ipadx=5)
for i in range(10):
    Entry(med).grid(row=i+1,column=0,padx=5,ipadx=5,pady=3)
    Entry(med).grid(row=i+1,column=1,padx=5,ipadx=5,pady=3)
    Entry(med).grid(row=i+1,column=2,padx=5,ipadx=5,pady=3)
    Entry(med).grid(row=i+1,column=3,padx=5,ipadx=5,pady=3)
Label(med).grid(row=i+2)
Button(med,text='Save',width=15).grid(row=i+3,column=2,stick=E+S,padx=5)
Button(med,text='Discard',width=15,command=med.destroy).grid(row=i+3,column=3,stick=W+S)
Label(med,text='\n\n').grid()
mainloop()
